name: task_management
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  animations: ^2.0.11
  firebase_core: ^3.10.1
  firebase_database: ^11.3.1
  firebase_ui_database: ^1.5.1
  flex_color_scheme: ^8.1.0
  flutter:
    sdk: flutter
  go_router: ^14.6.3
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
