name: Android APK Release

on:
  workflow_dispatch:

env:
  java_version: '17'
  flutter_version: '3.27.0'
  
jobs:
  android:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.java_version }}
          cache: 'gradle'

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
            /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.flutter_version }}
          
      - name: Flutter pub dependencies
        run: flutter pub get

      - name: Configure Keystore
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          GOOGLE_JSON_FILE: ${{ secrets.GOOGLE_JSON }}
          KEY_PROPERTIES_FILE: ${{ secrets.KEY_PROPERTIES }}
        run: |
          cd android
          base64 -d <<< "$PRIVATE_KEY" > key_file.p12
          base64 -d <<< "$KEY_PROPERTIES_FILE" > key.properties
          base64 -d <<< "$GOOGLE_JSON_FILE" > app/google-services.json

      - name: Build release version for testing purpose
        run: flutter build apk --build-name=1.0.${{ github.run_number }} --build-number=${{ github.run_number }} --no-pub --verbose --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          retention-days: 7
          path: build/app/outputs/flutter-apk/app-release.apk